language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/gce-ipx800-v4.git"
  - secure: LSBrVxYNcU0cUk2QRTNpYHdKnRclqzJ3CWC7ZNUGfb74SM7g17eOyUVgRhk7nmPCfxdaWMTIEUL25oYSwFxh9tjpEgVTjVCQLlOIQn1XPHScNMSxIuUe6QtCF4IxBwUDV4eAxkDWnqq7uMJgIjSfV16N/ZlmtjjC8Z3IU4ER+e4uq7V5+sv2GDgDWC2uxpu9ffli4yjNoPv2NdAuRiRq+aJiqi2BtwZjqHYJ0fYQ2dQc5mv59kP2bBuKtm8/WBYxik3ySfj2qif+sZFiFlHEFuUaU6SpY821+eJ/iKp+k10zp+MDSxDtjLZiHxy9WS+KAqgi6g9ahTHPPxRR+bzyk3v9sLAj12dq+tGt88n1Upy6HZgLe1mx/gAtcS6OwVWPQNPko0OVRyLjQmqudd+V89DBokocQxKx2TWHB3hU4klZQLNE+1E06tpIXjXO4vUZ5pgmTdfCPZavlsJ0/o34NeQHg0Hvzs37uQ0B4BtyvqzzmXddSxXyHjTj4HAxnlieZVji8em+odKrFDRQhwZlAuIGVoT9+oGj9u4eHLcPXuWgCeuKgZaKUFxh0jSYvo38nYpuS8a30FPSkw60ar55JAoVeZUI8vATpJnyJR0o74NxXvjNU4lbLJqrY/1Crbh1pieEdxPauxZw3aEjlJTxitNr0H2qcVo3jb93ND1GH50=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_653ad4abde11_key -iv $encrypted_653ad4abde11_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
